version: "2"
services:
  explorer:
    build: ./explorer
    restart: always
    ports: 
      - "80:8081"
  daemon:
    build: ./daemon
    restart: always
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: blockexuser
      MONGO_INITDB_ROOT_PASSWORD: Explorer!1
