version: "2"
services:
  reverseproxy:
    build: ./reverseproxy
    ports:
      - 80:80
    restart: always
    volumes:
      - ../public:/static
  api:
    build: ./api
    restart: always
  cron:
    build: ./cron
    restart: always
  daemon:
    build: ./daemon
    restart: always
  mongodb:
        image: mongo:latest
        environment:
          - MONGO_DATA_DIR=/data/db
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017