version: "2"
services:
  explorer:
    build: ./explorer
    restart: always
    ports: 
      - "80:8081"
  daemon:
    build: ./daemon
    restart: always
  mongodb:
        image: mongo:latest
        environment:
          - MONGO_DATA_DIR=/data/db
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017